name: "CloudFormation Deploy"
description: "Deploy a CloudFormation Template"
branding:
  icon: "upload-cloud"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  stackName:
    description: CloudFormation stack name.
    required: true
  templateFile:
    description: Path to your CloudFormation template file.
    required: true
  parameters:
    description: Stack parameters as string. Format is `key1=val1 key2=val2`. If your parameter value has whitespace in it, you'll have to use `parameterFile` instead.
    required: false
    default: ""
  parameterFile:
    description: Stack parameters as file. Format is one `key=val` per line.
    required: false
    default: ""
  capabilities:
    description: String defining required CloudFormation capabilities, eg `CAPABILITY_IAM`.
    required: false
    default: ""
  noExecuteChangeset:
    description: If defined, a CloudFormation change set will be created but not executed.
    required: false
    default: ""
