name: "CloudFormation Deploy"
description: "Deploy a CloudFormation Template"
branding:
  icon: "upload-cloud"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  stackName:
    description: CloudFormation stack name.
    required: true
  templateFile:
    description: Path to your CloudFormation template file.
    required: true
  parameters:
    description: Stack parameters. Format is `key1=val1 key2=val2`. If your parameter values have whitespace, use `parameterFile`.
    required: false
    default: ""
  parameterFile:
    description: File with stack parameters. Format is one `key=val` per line.
    required: false
    default: ""
  capabilities:
    description: Required CloudFormation capabilities, eg `CAPABILITY_IAM`.
    required: false
    default: ""
  noExecuteChangeset:
    description: If defined, create a CloudFormation change set but do not execute it.
    required: false
    default: ""
